name: Backend Production CI/CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    strategy:
      matrix:
        ip: [ "13.125.20.44", "43.202.67.1", "43.200.255.131", "3.34.40.75", "3.36.67.250", "3.35.206.138", "13.124.176.167", "13.124.207.254", "3.36.124.142", "52.79.248.241", "3.38.178.217", "3.39.6.32", "43.201.53.102", "54.180.132.75", "13.209.9.213", "3.35.134.57"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh

          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key.pem
          chmod 600 ~/.ssh/deploy_key.pem

          cat <<EOF > ~/.ssh/config
          Host backend
              HostName ${{ matrix.ip }}
              User ec2-user
              IdentityFile ~/.ssh/deploy_key.pem
              StrictHostKeyChecking no
              UserKnownHostsFile /dev/null
          EOF

      - name: Upload backend files to server
        run: |
          ssh backend "mkdir -p ~/backend"
          scp -r ./backend/* backend:~/backend/

      - name: Install dependencies
        run: |
          ssh backend <<'EOF'
          cd ~/backend
          npm ci
          EOF

      - name: Generate and upload .env file
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          PASSWORD_SALT: ${{ secrets.PASSWORD_SALT }}
          REDIS_HOST: 13.125.133.227
          REDIS_PORT: 6379
          PUBSUB_HOST: 10.0.11.63
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        run: |
          echo "Generating .env file"
          cat > .env <<EOF
          MONGO_URI=${MONGO_URI}
          JWT_SECRET=${JWT_SECRET}
          OPENAI_API_KEY=${OPENAI_API_KEY}
          ENCRYPTION_KEY=${ENCRYPTION_KEY}
          REDIS_HOST=${REDIS_HOST}
          REDIS_PORT=${REDIS_PORT}
          PUBSUB_HOST=${PUBSUB_HOST}
          REDIS_PASSWORD=${REDIS_PASSWORD}
          PASSWORD_SALT=${PASSWORD_SALT}
          CLOUDFRONT_URL=https://file.goorm-ktb-016.goorm.team/
          AWS_REGION=ap-northeast-2
          S3_BUCKET_NAME=ktb-bootcamp-chat-16
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EOF

          scp .env backend:~/backend/.env

      - name: Start PM2 process on port 5000
        run: |
          ssh backend "
            cd ~/backend &&
            pm2 delete backend-5000 || true &&
            PORT=5000 pm2 start server.js --name backend-5000 --env production
          "
